language: php

php:
  - 7.4

cache:
  directories:
    - vendor

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction

script:
  - composer phpcs-auto-check-project
  - composer phpunit
