name: tests

on:
  push:
  pull_request:

jobs:
  php-74:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          ini-values: error_reporting=E_ALL, display_errors=On

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Execute tests
        run: composer tests

  php-80:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: none
          ini-values: error_reporting=E_ALL, display_errors=On

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Execute tests
        run: composer tests

  php-81:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          ini-values: error_reporting=E_ALL, display_errors=On

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Execute tests
        run: composer tests
